### ISSUE TITLE
Improper Formatted Package

### ISSUE THREAD

**Issue by DrewOJensen** [lacides/ember-cli-fixture-loader#6]
I installed using your guide and tried creating a fixture of a model and I get the following error.

MacBook-Pro:app Animal$ ember generate fixture league
The package `ember-cli-fixture-loader` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/Animal/Documents/Git/App/node_modules/ember-cli-fixture-loader`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
The `ember-cli-fixture-loader` addon could not be found at `/Users/Animal/Documents/Git/App/node_modules/ember-cli-fixture-loader`.

I double checked to make sure that the ember-cli-fixture-loader folder was in the node-modules and it is. I'm using up to date ember & ember-data. Any ideas?

**Comment by lacides** [comment]
hey @DrewOJensen.
Yeah, it was missing an entry point script. I just released a new version that includes it.
Thanks for the heads up!
